baseURL = "https://zerodha.tech"
languageCode = "en-us"
title = "Zerodha Tech Blog"
paginate = 10
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
subtitle = "Technology blog of India's largest stock broker"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "blog"
      name = "Blog"
      url = "/blog"
      weight = 2

   [[menu.header]]
      identifier = "projects"
      name = "Projects"
      url = "/projects"
      weight = 3
