baseURL = "https://zerodha.tech"
languageCode = "en-us"
title = "Zerodha Tech Blog"
paginate = 50
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-75485182-2"

[params]
subtitle = "Technology blog of India's largest stock broker"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "blog"
      name = "Blog"
      url = "/blog"
      weight = 2

   [[menu.header]]
      identifier = "projects"
      name = "Projects"
      url = "/projects"
      weight = 3

   [[menu.header]]
      identifier = "stack"
      name = "Stack"
      url = "/stack"
      weight = 4

[markup]
   [markup.goldmark.renderer]
      unsafe = true
